name: Build Debug APK
on:
  workflow_dispatch:
env:
  FLUTTER_VERSION: "3.35.6"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Remove proprietary dependencies
        run: sh scripts/remove_proprietary_dependencies.sh || true
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: \${{ env.FLUTTER_VERSION }}
      - name: Dependencies
        working-directory: app
        run: flutter pub get
      - name: Build Debug APK
        working-directory: app
        run: flutter build apk --debug
      - name: Upload Debug APK
        uses: actions/upload-artifact@v6
        with:
          name: localsend-debug-apk
          path: app/build/app/outputs/flutter-apk/*.apk
